apiVersion: v2
name: databackend-chart
description: A Helm chart to deploy DataBackend to Kubernetes

type: application

version: ${project.version}

appVersion: "${project.version}"

dependencies:
  - name: postgresql
    version: "13.2.30"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: databases.databackend.internal