apiVersion: v2
name: databackend-chart
description: A Helm chart to deploy DataBackend to Kubernetes

type: application

# This is the chart version.
version: 1.2.0

# Docker image version number
appVersion: 1.2.0

dependencies:
  - name: postgresql
    version: "13.2.30"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: databases.databackend.internal