# Default values for databackend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/starwitorg/databackend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
nameOverride: ""
fullnameOverride: ""

app:
  context_path: "/databackend"

auth:
  enabled: false
  keycloak_url: https://hostname/realms/databackend
  client_id: databackend
  client_secret: databackend 

databases:
  internal: 
    url: localhost:5432
    database: databackend
    username: databackend
    password: databackend
  sae:
    url: localhost:5432
    database: sae
    username: sae
    password: sae
    table_name: detection
  analytics:
    url: localhost:5432
    database: analytics
    username: analytics
    password: analytics

ingress:
  enabled: true
  annotations: 
    cert-manager.io/issuer: letsencrypt-prod
  hosts:
    - host: test.starwit.de
      paths:
        - path: /databackend
          pathType: ImplementationSpecific
  tls: 
    - secretName: test.starwit.de
      hosts:
        - test.starwit.de

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8081

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
