app:
  context_path: "/databackend"

analyticsJobRunInterval: 2000

sae:
  redisStreamPrefix: geomapper
  redisHost: localhost
  redisPort: 6379

databases:
  databackend: 
    internal: true
    # `host` and `port` are only relevant if `internal` is `false`
    host: local.starwit.de
    port: 31222
    database: databackend
    username: databackend
    password: databackend
  analytics:
    host: local.starwit.de
    port: 31222
    database: analytics
    username: analytics
    password: analytics 

ingress:
  enabled: false
  annotations: 
    cert-manager.io/issuer: letsencrypt-prod
  hosts:
    - host: local.starwit.de
      paths:
        - path: /databackend
          pathType: ImplementationSpecific
  tls: 
    - secretName: local.starwit.de
      hosts:
        - local.starwit.de