pullSecret:
  user: "docker"
  password: "password"
  registryurl: "docker.internal.starwit-infra.de"

app:
  context_path: "/databackend"

auth:
  enabled: false
  keycloak_url: https://hostname/realms/databackend
  client_id: databackend
  client_secret: databackend 

databases:
  internal: 
    url: local.starwit.de:31222
    database: databackend
    username: databackend
    password: databackend
  sae:
    url: local.starwit.de:31222
    database: sae
    username: sae
    password: sae
    table_name: detection
  analytics:
    url: local.starwit.de:31222
    database: analytics
    username: analytics
    password: analytics 

ingress:
  enabled: true
  annotations: 
    cert-manager.io/issuer: letsencrypt-prod
  hosts:
    - host: local.starwit.de
      paths:
        - path: /databackend
          pathType: ImplementationSpecific
  tls: 
    - secretName: local.starwit.de
      hosts:
        - local.starwit.de