app:
  context_path: "/databackend"

analyticsJobRunInterval: 2000

databases:
  databackend: 
    internal: true
    url: local.starwit.de:31222
    database: databackend
    username: databackend
    password: databackend
  sae:
    redisStreamPrefix: geomapper
    redisHost: localhost
    redisPort: 6379
    fetchDataInterval: 1000
  analytics:
    url: local.starwit.de:31222
    database: analytics
    username: analytics
    password: analytics 

ingress:
  enabled: false
  annotations: 
    cert-manager.io/issuer: letsencrypt-prod
  hosts:
    - host: local.starwit.de
      paths:
        - path: /databackend
          pathType: ImplementationSpecific
  tls: 
    - secretName: local.starwit.de
      hosts:
        - local.starwit.de