version: "3.9"
services:
  databackend-db:
    container_name: databackend-db
    image: postgres:latest
    environment:
      POSTGRES_DB: databackend
      POSTGRES_USER: databackend
      POSTGRES_PASSWORD: ${DB_PW_databackend}
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U databackend'] # <<<---
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - databackend-db:/var/lib/postgresql/data
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - backend
    restart: unless-stopped
      
  databackend:
    image: databackend:latest
    depends_on:
      databackend-db:
        condition: service_healthy
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://databackend:5432/databackend?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: databackend
      SPRING_DATASOURCE_PASSWORD: ${DB_PW_databackend}
      KEYCLOAK_AUTH-SERVER-URL: https://${DOMAIN}/auth
      SERVER_USE_FORWARD_HEADERS: "true"
      SERVER_FORWARD_HEADERS_STRATEGY: FRAMEWORK
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

volumes:
  databackend-db:

 # Networks to be created to facilitate communication between containers
networks:
  backend:

