version: "3.9"
services:
  observatory-db:
    container_name: observatory-db
    image: postgres:latest
    environment:
      POSTGRES_DB: observatory
      POSTGRES_USER: observatory
      POSTGRES_PASSWORD: ${DB_PW_observatory}
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U observatory'] # <<<---
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - observatory-db:/var/lib/postgresql/data
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - backend
    restart: unless-stopped
      
  observatory:
    image: observatory:latest
    depends_on:
      observatory-db:
        condition: service_healthy
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://observatory:5432/observatory?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: observatory
      SPRING_DATASOURCE_PASSWORD: ${DB_PW_observatory}
      KEYCLOAK_AUTH-SERVER-URL: https://${DOMAIN}/auth
      SERVER_USE_FORWARD_HEADERS: "true"
      SERVER_FORWARD_HEADERS_STRATEGY: FRAMEWORK
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

volumes:
  observatory-db:

 # Networks to be created to facilitate communication between containers
networks:
  backend:

