{{ $internal_username := required "User must be set!" .Values.pullSecret.user }}
{{ $internal_password := required "Password must be set (can also be a token)!" .Values.pullSecret.password }}
{{ $internal_url := required "URL must be set!" .Values.pullSecret.registryurl }}

apiVersion: v1
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"\"}}}" $internal_url $internal_username $internal_password | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
