{{- if .Values.auth.enabled }}
{{- $clientid := required ".auth.client_id not set" .Values.auth.client_id }}
{{- $clientsecret := required ".auth.client_secret not set" .Values.auth.client_secret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak
  namespace: {{ .Release.Namespace }}
data:
  client_id: {{ .Values.oauth.clientid | b64enc }}
  client_secret: {{ .Values.oauth.clientsecret | b64enc }}
{{- end }}
