apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "databackend.fullname" . }}
  labels:
    {{- include "databackend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "databackend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "databackend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "databackend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.databases.internal.url }}/{{ .Values.databases.internal.database }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.databases.internal.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.databases.internal.password }}

            - name: SAE_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.databases.sae.url }}/{{ .Values.databases.sae.database }}
            - name: SAE_DATASOURCE_USERNAME
              value: {{ .Values.databases.sae.username }}
            - name: SAE_DATASOURCE_PASSWORD
              value: {{ .Values.databases.sae.password }}
            - name: SAE_TABLENAME
              value: {{ .Values.databases.sae.table_name }}

            - name: ANALYTICS_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.databases.analytics.url }}/{{ .Values.databases.analytics.database }}
            - name: ANALYTICS_DATASOURCE_USERNAME
              value: {{ .Values.databases.analytics.username }}
            - name: ANALYTICS_DATASOURCE_PASSWORD
              value: {{ .Values.databases.analytics.password }}              

            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.app.context_path | quote }}
            {{- if .Values.auth.enabled }}  
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI
              value: {{ .Values.auth.keycloak_url }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT-ID
              valueFrom:
                secretKeyRef:
                  key:  client_id
                  name: {{ .Release.Name }}-keycloak
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT-SECRET
              valueFrom:
                secretKeyRef:
                  key:  client_secret
                  name: {{ .Release.Name }}-keycloak
            {{- end }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /{{ include "databackend.fullname" . }}/monitoring/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /{{ include "databackend.fullname" . }}/monitoring/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
