name: Build and publish latest image

on:
  workflow_dispatch:
    inputs:
      push:
        description: Whether to push the built docker image
        default: false
        type: boolean
  workflow_call:
    inputs:
      push:
        description: Whether to push the built docker image
        default: false
        type: boolean
    secrets:
      VISION_MAVEN_READ_TOKEN:
        description: Token for Github packages on vision-api and vision-lib with read access
        required: true

env:
  IMAGE_NAME: databackend

jobs:
  build:
    name: "Build and publish with build number"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.2

    - uses: s4u/maven-settings-action@v3.0.0
      with:
        repositories: |
          [{
            "id": "visionapi",
            "name": "vision-api",
            "url": "https://maven.pkg.github.com/starwit/vision-api",
            "snapshots": {"enabled": true}
          },{
            "id": "visionlib",
            "name": "vision-lib",
            "url": "https://maven.pkg.github.com/starwit/vision-lib",
            "snapshots": {"enabled": true}
          }]
        servers: |
          [{
            "id": "visionapi",
            "username": "flonix8", 
            "password": "${{ secrets.VISION_MAVEN_READ_TOKEN }}"
          },{
            "id": "visionlib",
            "username": "flonix8", 
            "password": "${{ secrets.VISION_MAVEN_READ_TOKEN }}"
          }]

    - name: Get version from pom.xml
      run: |      
        echo "VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )-${{ github.run_number }}" >> $GITHUB_ENV
    - name: Get Maven settings.xml location
      run: |      
        echo "SETTINGS_XML=$HOME/.m2/settings.xml" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: ${{ inputs.push }}
        tags: ${{ vars.DOCKERHUB_ORG }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        secret-files: |
          mvn-settings=${{ env.SETTINGS_XML }}
