name: Build and Publish

on:
  push:
  pull_request:
    branches: [ main, versionupgrade ]
  workflow_dispatch:

env:
  IMAGE_NAME: databackend
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg

jobs:
  build:
    name: "Building project with Java 21"
    #runs-on: [self-hosted, linux, X64]
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get helm
        uses: azure/setup-helm@v3

      - name: login to Helm registry
        run: helm registry login registry-1.docker.io -u starwit -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: run helm package
        working-directory: deployment/helm
        run: helm package databackend
      - name: get version number
        working-directory: deployment/helm/databackend
        run: |
          echo "HELM_VERSION=$(grep version: Chart.yaml | awk '{print $2}')" >> $GITHUB_ENV
      - name: run helm push
        working-directory: deployment/helm
        run: helm push databackend-${{ env.HELM_VERSION }}.tar.gz oci://registry-1.docker.io/starwitorg

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: get version from pom.xml
        run: |
          echo "VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )" >> $GITHUB_ENV
        id: get_version
      - name: check version number
        run: echo "version number ${{ env.VERSION }}"

      - name: Build with Maven
        run: mvn clean -B package --file pom.xml
        env:
          CI: false

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_ORG }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}